version: '3'

services:

  php:
    image: devilbox/php-fpm-7.4:latest
    volumes:
      - ./../../src:/app
    container_name: ${COMPOSE_PROJECT_NAME}-web-app-php
    restart: always

  web:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}-web-app-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../../src:/app
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php